### ISSUE TITLE
Link GitHub & Email accounts if both have same email

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-storefront#100]
GIVEN An Anonymous user AND An User already have account by email/password.
WHEN an user clicks on Sign-in by GitHub, Facebook and etc 
AND GitHub account has got same email
THEN GitHub account and Email account should be linked, instead of creation of new account

Acceptance criteria:
- For example, prepare GitHub account + configure email address
- Register a new account in VirtoCommerce (email+password). The email should be same 
- Sign-out
- Sign-in with GitHub Account
- GitHub account and Email account should be linked, instead of creation of new account

**Comment by Flanker72** [comment]
No priority for current releases.
