### ISSUE TITLE
Theme and Pages changes aren't applied without storefront restart 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-storefront#149]
Add the themes or pages content as a symlink to the cms-content folder and any changes with these files aren't applied then on the storefront.

**Technical details:**
That happens due to that fact that  FileSystemWatcher is used to watch the directory and can not watch the symbolic link or directory through a symbolic link.

Need to find the technical solution to this issue.

There is place in the code where file system resource watched
https://github.com/VirtoCommerce/vc-storefront-core/blob/master/VirtoCommerce.Storefront/Domain/ContentBlobProviders/FileSystemContentBlobProvider.cs#L129

**Comment by anton-abyzov** [comment]
PhysicalFilesWatcher overrides Created delegate (we cant extend or get rid of PhysicalFilesWatcher), so there is no straight-forward way to adjust symlinks. It works for only root folder (cms-content) as symlink, but all symlinks inside are not working.

**Comment by tatarincev** [comment]
We didn't find a a reasonable solution to this issue

**Comment by asvishnyakov** [comment]
Don't close, move to on hold them

**Comment by n2pro** [comment]
1. Instead of creating symbolic links, use physical copying.
2. Clear the cache after making changes here (work around)
          VirtoCommerce.Storefront -> Domain -> StaticContent -> StaticContentService ->  LoadStoreStaticContent
          VirtoCommerce.LiquidThemeEngine -> ShopifyLiquidThemeEngine ->  ReadTemplateByName

**Comment by Flanker72** [comment]
This is theme-related issue. Current SPA theme have no watching. Liquid engine is deprecated and will be removed in further releases.
