### ISSUE TITLE
AllProducts property is missing from contents

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-storefront#163]
I should be able to access any product in the current store catalog using the following syntax within any liquid page:

all_products['code']

### Expected behavior
Should return the product info.

**Comment by tlacure17** [comment]
@tatarincev Do you have any idea when this change will be complete?

**Comment by tatarincev** [comment]
@tlacure17  We can increase the priority of this improvements, but it will definitely not be this week.

**Comment by Flanker72** [comment]
Liquid engine will be deprecated soon. No plans to extend current functionality. All data management should be implemented within the particular theme (vc-theme-b2b-vue) using XAPI data access layer.
