### ISSUE TITLE
Add support for alternative theme locations

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-storefront#203]
**Current behavior:**
Now ThemeEngine could search for the theme in the following places:
- \cms-content\Themes\{storeId}\{defaultThemeName} (if store has DefaultThemeName dynamic property filled)
- \cms-content\Themes\{storeId}\default (if DefaultThemeName is not filled for store)

**Proposed changes:**
Need to change Theme folder search logic with the one described below.

Search these locations in such order until theme is found:
- \cms-content\Themes\{storeId}\{defaultThemeName}
- \cms-content\Themes\{storeId}\default
- \cms-content\Themes\{storeId}\
- \cms-content\Themes\

**Technical details:**
Extend [CurrentThemePath](https://github.com/VirtoCommerce/vc-storefront-core/blob/ac4ebc8dac299a45f000b83335f9111ccd0a250e/VirtoCommerce.LiquidThemeEngine/ShopifyLiquidThemeEngine.cs#L120) with the logic described above.
To check if folder contains theme, you could check for folder existence, and for existence of 'index.liquid' file in \templates, \assets and other possible subfolders we try to search the template.

**Comment by Flanker72** [comment]
This issue is not relevant to current storefront roadmap.
