### ISSUE TITLE
LiquidThemeEngine - support for 'section' theme tag? 

### ISSUE THREAD

**Issue by rayprestige** [VirtoCommerce/vc-storefront#230]
The documentation claims that shopify themes are fully supported. However I see many of the shopify themes have 'section' and theme tags like `{% section 'product-template' %}` has been used  a lot. 

Do we have plan for adding support for 'section' any time soon? 

This is more of a feature quest than an issue, thanks. 

Cheers, 
Ray

**Comment by rayprestige** [comment]
I had a play with a couple of basic shopify template with virtoCommerce, it looks like DotLiquid and LiquidThemeEngine has quite some catch up for Shopify tags. 

Apart from Section theme tag, Liquid Filter tags are not supported(https://help.shopify.com/en/themes/liquid/filters); Referencing svg in a separate .liquid file is not supported (e.g. in Spotify themes (Narrative, Debut, Boundless). 

I'd consider being able to choose from thousands of existing Shopify themes is one of the biggest strength for Virtocommerce. A powerful templating engine will give people a great head start using the platform. 

I realised switching to Scriban is on the scope for the future, wish you guys the best of luck if you had plan to do it any time soon.

**Comment by Flanker72** [comment]
Liquid engine support will be deprecated soon. No plans to extend it somehow.
