### ISSUE TITLE
Routing test reorganization

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-storefront#255]
Now all routing tests are unified in single `RoutingTests` class. This prevents parallel execution.

As proposed by @asvishnyakov, they could be organized in several different tests with common base class.

Example:
[Routing.zip](https://github.com/VirtoCommerce/vc-storefront-core/files/3147359/Routing.zip)

**Comment by Flanker72** [comment]
Current routing is based on per-theme basis. Storefront have no significant routing capabilities in current release.
