### ISSUE TITLE
Add [ValidateAntiForgeryToken] attribute to all form post handlers

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-storefront#27]
Need to make sure request came from the current site.

**Comment by tatarincev** [comment]
@eMazeika  could you duplicate these changes in https://github.com/VirtoCommerce/vc-storefront-core?

**Comment by eMazeika** [comment]
@tatarincev changes were duplicated in https://github.com/VirtoCommerce/vc-storefront-core/pull/21

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.0.2
