### ISSUE TITLE
Memory cache keys include external input

### ISSUE THREAD

**Issue by sjroesink** [VirtoCommerce/vc-storefront#270]
Currently different cache keys include values from the query strings. This means anyone can let the app run out of memory by simply making a lot of requests with random values in the query string.

One example is the product search; in [the ProductSearchCriteria class](https://github.com/VirtoCommerce/vc-storefront-core/blob/7d0ea0068f7d4c099c3c4880dba62b3dc8f1998d/VirtoCommerce.Storefront.Model/Catalog/ProductSearchCriteria.cs) query string values are directly parsed to search properties, which in turn are used in the cache key.

The [memory cache guidelines](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.2#cache-guidelines) also state that external input should not be used as cache keys.

**Comment by Woland2k** [comment]
@tatarincev this is a serious issue, we shouldn't be caching request per user

**Comment by tatarincev** [comment]
@sjroesink When I designed caching for storefront I was convinced that the implementation of InMemoryCaching  is included one of cache replacement policies such as LRU, MRU or other. And system will carry about replacement and eviction not frequently used data from cache, but reality was different. 
Thanks for your valuable recommendation we will definitely fix this situation in next releases.

**Comment by sjroesink** [comment]
@tatarincev Okay thanks.
For now I disabled caching of the catalog searches in our project because it was already causing a problem when a security bot was scanning the site with random query strings.
I'll keep an eye open for the next release.

**Comment by Flanker72** [comment]
Current storefront doesn't use cache for most cases. We use XAPI as data access layer and Vue SPA as the frontend. For now vc-storefront architecture is significantly changed.
