### ISSUE TITLE
Create and manage multiple shopping carts

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-storefront#28]
The cart service provides an interface for users to be able to create and manage multiple shopping carts.

While Virto Commerce Cart module can support multiple shopping carts, the storefront cart service should provides the user interface to view, select and delete multiple carts.

The module also updates the logic to determine which cart is currently active. 

## Feature: B2C multiple shopping carts
  Scenario: Add to list
    Given I have product and several shopping carts (list)
    When I ask to add a product into selected list 
    Then 1 item should be added into Selected List

  Scenario: Create a new list (Permission required)
    Given the Your Lists page is open
    When the user clicks Create a list
    and the user types list name
    and then click Create List button 
    Then a new list with [list name] should be visible in Your Lists. 

  Scenario: View Your lists
  Scenario: View Shared lists

  Scenario: Remove own list
    Given the Your Lists page is open
    When the user clicks Delete button 
    Then confirmation message should be 
    When the user approves confirmation
    Then list should be removed from Your Lists. 

  Scenario: View products in list 

  Scenario: Share list by link (Permission required)

  Scenario: Share list by email (Permission required)

  Scenario: Add shared list into my list (Permission required)

  Scenario: See shared with me lists

  Scenario: Start checkout flow for selected list (Permission required)

**Default shopping list**
1. Shopping List (Private)
2. Wish list (Public)

## More
**Administer carts**
Permission required for viewing, sharing and setting multiple carts.
**Delete own carts**
Allow users to be able to delete a own cart.

## Technical implementation:
* Create a new angular service
* Create a new API controller 
* Add set angular controls into Profiles to My List
* Add set angular controls into theme to add and display list of cart on storefront

## Examples
Screenshots:
![image](https://user-images.githubusercontent.com/7639413/28796741-0110c2d8-763f-11e7-8e13-edad7590bd79.png)

![image](https://user-images.githubusercontent.com/7639413/28796820-4fece580-763f-11e7-93f5-e1ee900316d3.png)

![image](https://user-images.githubusercontent.com/7639413/28796781-249275bc-763f-11e7-8993-d1bcb4603125.png)

![image](https://user-images.githubusercontent.com/7639413/28796760-11aa3836-763f-11e7-81ac-de87dbbab264.png)

**Comment by OlegoO** [comment]
**Technical implementation:**
* Create a new angular service
* Create a new API controller 
* Add set angular controls into Profiles to My List
* Add set angular controls into theme to add and display list of cart on storefront

**Comment by vkrashenko** [comment]
![add settings](https://user-images.githubusercontent.com/29459286/29555187-2215efdc-8722-11e7-91f3-39be4a870cb6.jpg)

**Comment by vkrashenko** [comment]
![creation](https://user-images.githubusercontent.com/29459286/29555226-44c6bc6e-8722-11e7-9f9d-4da024cb0931.jpg)

**Comment by vkrashenko** [comment]
![demolists-iloveimg-compressed](https://user-images.githubusercontent.com/29459286/31197355-1e43024a-a951-11e7-82e4-6cd62db152ea.gif)

**Comment by tatarincev** [comment]
It seems this functionality already implemented as wish lists on the storefront.
You may reopen this issue if it has been closed in error.
