### ISSUE TITLE
MutablePagedList json converter execution time enhancement

### ISSUE THREAD

**Issue by arsen74** [VirtoCommerce/vc-storefront#284]
MutablePagedListAsArrayJsonConverter class uses in almost each http calls from Storefront to Platform API.
Every calls engages heavy reflection API operation and execution time of each operation is about 8ms.
For example, product details page on Storefront side makes minimum 5 calls to Platform API.

[
![MutablePagedListAsArrayJsonConverter](https://user-images.githubusercontent.com/24797428/62162535-e9df3680-b331-11e9-9b84-0455bde3fb57.png)
]

If we add to cache calls to reflection API we could save about 50% time for every request.

For example, we can add simple cache:
`var genericType = value.GetType().GetGenericArguments()[0];

            var methodInfo = _cachedToListInvoker.GetOrAdd(
                genericType,
                (input) =>
                {
                    return typeof(Enumerable)
                        .GetMethod("ToList")
                        .MakeGenericMethod(genericType);
                });

            //Force serialize MutablePagedList type as array, instead of dictionary
            var result = JArray.FromObject(methodInfo.Invoke(null, new object[] { value }), _serializer);`

Prototype and benchmark are here - 
[VirtoCommerce.Storefront.Benchmarks.zip](https://github.com/VirtoCommerce/vc-storefront-core/files/3448739/VirtoCommerce.Storefront.Benchmarks.zip)

This simple improvements reduced execution time:
![Benchmark-1](https://user-images.githubusercontent.com/24797428/62163035-f44e0000-b332-11e9-9e08-8615acfcc701.png)

Also we can add implementation cache on code generation via Expressions - execution time will be reduced even more

**Comment by Flanker72** [comment]
Not needed for current releases. All data manipulation is migrated to XAPI data access layer.
