### ISSUE TITLE
Initial setup must be simplified

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-storefront#29]
@Woland2k commented on [Thu Sep 15 2016](https://github.com/VirtoCommerce/vc-platform/issues/615)

Typical user wants to setup virto commerce with a minimum effort and edit the default store design. In the current platform such approach is too complicated. In order to simplify this, we need to remove certain dependencies:
1. Shouldn't require VS.NET.
2. Should be possible to edit sample store theme right from the admin.
3. Simple deployment on azure cloud.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
