### ISSUE TITLE
Log out user on store change

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-storefront#299]
Version info: 
- Storefront version: latest

### Expected behavior
User is logged out if changing to non-linked store
### Actual behavior
User stays logged in in a non-linked store
### Steps to reproduce
1. sing-in to Electronics store
2. Change store to B2B
3. page for registered user is displayed

**Comment by Flanker72** [comment]
Not planned for current releases. This issue is not longer relevant.
