### ISSUE TITLE
Fix "Go to quote request" link

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-storefront#301]
Version info:
- Storefront version: latest

### Expected behavior
Quote details displayed
### Actual behavior
"QUOTE REQUEST IS CURRENTLY EMPTY."
### Steps to reproduce
1. sign in
2. open some product details
3. click "Add to quote"
4. "PRODUCT IS ADDED TO QUOTE REQUEST" dialog is shown. Click "Go to quote request"
5. "QUOTE REQUEST IS CURRENTLY EMPTY." gets displayed

**Comment by eMazeika** [comment]
any status update?

**Comment by eMazeika** [comment]
swagger for quotes is corrupted:  https://admin-demo.virtocommerce.com/docs/VirtoCommerce.Quote/v1
Could it be related to this?

**Comment by Flanker72** [comment]
Quote management will be redesigned in vc-theme-b2b-vue implementation.
