### ISSUE TITLE
Fix "Submit quote request"

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-storefront#302]
Please provide detailed information about your issue, thank you!

Version info:
- Storefront version: latest

### Expected behavior
Quote request is submitted and an appropriate message displayed
### Actual behavior
Blue "500 Internal server error." page displayed
### Steps to reproduce
1. Add product to quote
2. Open quote details (from the link on the top)
3. Fill the form, click "Submit quote request"
4. Blue "500 Internal server error." page displayed

**Comment by eMazeika** [comment]
any progress?

**Comment by eMazeika** [comment]
swagger for quotes is corrupted: https://admin-demo.virtocommerce.com/docs/VirtoCommerce.Quote/v1
Could it be related to this?

**Comment by Flanker72** [comment]
Quote management will be redesigned and implemented in vc-theme-b2b-vue. All data should be handled using XAPI data access layer, storefront won't have any APIs for this.
