### ISSUE TITLE
Product and Dynamic properties is not loaded for LineItem in cart

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront#32]

**Comment by zhangpengchen** [comment]
Seem the issue still occur, dynamic properties were not saved for LineItem in cart.

**Comment by zhangpengchen** [comment]
A small tip for someone who could not save dynamic properties or retrieve dynamic properties correctly for LineItem in cart. 

- Please remember to define dynamic property in Virto portal
- Remember to specify the value type in your store front also, by default it's using 'Undefined'  and value will be stored in LongTextValue.

**Comment by asvishnyakov** [comment]
Probably only DynamicProperties not loading now

**Comment by Flanker72** [comment]
All queries for now are performed using XAPI data engine. Issues with Dynamic Properties are resolved during vc-storefront upgrade.
