### ISSUE TITLE
Move default (Electronic) theme to own repository

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-storefront#33]
Move default (Electronic) theme into own repository.
It should provide ability 
- install default (Electronic) into azure.
- create a new theme with fork 
- add version manifest
- create theme release

- [x] Use Gulp task to create JS, CSS, HTML Bundles (Bundle, MIN, + Source MAP)
- [x] Use snippets to support DEBUG and RELEASE mode
- [x] Update bundle version (No Cache)
- [x] Check that source map works as expected
- [x] Clear code related to theme inheritances (ShopifyLiquidThemeEngine.cs settings and theme resources resolving, BundleConfig.cs, BundleFilters.cs, Startup.cs - global theme blob provider registration)
- [x] Display user friendly message if theme is not found (see example how it done for 'NoStore' https://github.com/VirtoCommerce/vc-storefront/blob/master/VirtoCommerce.Storefront/App_Start/FilterConfig.cs#L48)
- [x] Move theme to own repository
- [x] Inherit Clothing and B2B themes from default theme as fork
- [x] Merge vc-default-theme to https://github.com/VirtoCommerce/vc-demo-theme 
- [x] Update documentations:
  - [x] [storefront-source-code-getting-started](https://virtocommerce-public-staging.azurewebsites.net/docs/vc2devguide/deployment/storefront-deployment/storefront-source-code-getting-started)
  - [x] [working with bundles](https://virtocommerce-public-staging.azurewebsites.net/docs/vc2devguide/working-with-storefront/bundles)
  - [x] [theme-development](https://virtocommerce-public-staging.azurewebsites.net/docs/vc2devguide/working-with-storefront/theme-development)
  - [x] Edit [readme.md](https://github.com/VirtoCommerce/vc-default-theme/blob/dev/README.md)
    - [x] insert theme overview diagram
    - [x] edit paragraph for bundles (need code example instead word explanation)
- [x] Remake NoTheme page (should contain information about all used paths for themes discover and also link to detailed instructions how to right link theme folders)
- [ ] Setup CI for three themes (vc-material, vc-demo-theme, vc-b2b-theme) in demo.virtcommerce.com 
- [ ] Update sample data (remove all themes from sample data for demo, include  fresh  material and electronics themes version for regular sample data) also remove version information from file contains sample data for demo.
- [x] Publish theme release

**Comment by OlegoO** [comment]
https://github.com/VirtoCommerce/vc-storefront/tree/dev-gulp-bundle

## Use Gulp task to create JS, CSS, HTML Bundles (Bundle, MIN, + Source MAP)
- added  package.json
- added min gulp tasks (gulpfile.js) to create bundles
- added bundleconfig.json to describe bundles:  

### Usage
````````
gulp -b "D:\Projects\git\vc-storefront\VirtoCommerce.Storefront" --color --gulpfile "D:\Projects\git\vc-storefront\VirtoCommerce.Storefront\Gulpfile.js" min

````````
...
    {
        "outputFileName": "App_Data/Themes/default/assets/static/bundle/scripts.js",
        "inputFiles": [
            "App_Data/Themes/default/assets/modernizr.min.js",
            "App_Data/Themes/default/assets/interactor.js",
            "App_Data/Themes/default/assets/ideal-image-slider.min.js",
            "App_Data/Themes/default/assets/ideal-image-slider-bullet-nav.js",
            "App_Data/Themes/default/assets/ideal-image-slider-captions.js",
            "App_Data/Themes/default/assets/js/*.js"
        ]
    },
...
````````

## Use snippets to support DEBUG and RELEASE mode
- added bundle.liquid as default snippet.
The snippet injects Debug or Release script depends from VirtoCommerce:Storefront:OptimizeStaticContent
````````
{%- if application_settings['VirtoCommerce:Storefront:OptimizeStaticContent'] == 'true' -%}
        
        
{%- else -%}
        
        
{%- endif -%}
``````````

## Update bundle version (No Cache)
- added snippet gulp tasks to create theme snippets, which can be use in theme

account-scripts.liquid
``````````
{%- if application_settings['VirtoCommerce:Storefront:OptimizeStaticContent'] == 'true' -%}
        {{ 'bundle/account-scripts.min.js?ver=aef9721c2f8b' | static_asset_url | script_tag }}
{%- else -%}
        {{ 'bundle/account-scripts.js?ver=aef9721c2f8b' | static_asset_url | script_tag }}
{%- endif -%}
``````````

theme.liquid
``````````
    {% include 'bundle/styles' %}
``````````

**Comment by OlegoO** [comment]
## Linting with Virto Commerce ESLint config.
````````
gulp -b "VirtoCommerce.Storefront" --color --gulpfile "VirtoCommerce.Storefront\Gulpfile.js" lint
````````

## Create bundles
````````
gulp -b "VirtoCommerce.Storefront" --color --gulpfile "VirtoCommerce.Storefront\Gulpfile.js" min
````````
The script will publish new bundle files into:
vc-storefront\VirtoCommerce.Storefront\App_Data\Themes\default\assets\static\bundle

## Create snippets
````````
gulp -b "VirtoCommerce.Storefront" --color --gulpfile "VirtoCommerce.Storefront\Gulpfile.js" snippet
````````
The script will publish new snippets files into:
vc-storefront\VirtoCommerce.Storefront\App_Data\Themes\default\snippets\bundle 

## How to build theme
Start default tasks

**Comment by asvishnyakov** [comment]
CI for dev/qa complete, Sample data integration with CI will be created a little bit later. On hold until this task will be completed

**Comment by asvishnyakov** [comment]
@OlegoO Did theme CI integrated with sample data?
