### ISSUE TITLE
Unable to delete product from the list after adding all products to the cart.

### ISSUE THREAD

**Issue by akak1977** [VirtoCommerce/vc-storefront#350]
Preconditions: you have at least one wishlist with one product

Steps to reproduce:
1. Log in as a user(qa/123456Qw)
2. Open list from preconditions.
3. Press the "Add all products" button.
4. Try to delete one from the list.

Actual result: product isn't removed

5. Refresh the page.

Actual result: product isn't removed. Another same list is created.
Expected result: product is removed.

Note: when you delete the created list, the product can be deleted.

**Comment by Flanker72** [comment]
List management is redesigned to work with XAPI using named carts. Storefront now isn't responsible for handling any APIs.
