### ISSUE TITLE
Footer >404, when click on one of the quick links except "Terms & Conditions":

### ISSUE THREAD

**Issue by akak1977** [VirtoCommerce/vc-storefront#351]
Reprosteps:
1. Scroll down till the end of the page;
2. Click on any quick link except "Terms & Conditions";
3. 404 appears itstead of page.
It seems it's a problem with URL building. Content module returns URL with ~/ prefixe. But storefront interpret it incorrectly.

**Comment by Flanker72** [comment]
All links management should be made within the particular theme implementation.
