### ISSUE TITLE
Display price ranges

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-storefront#36]
@tatarincev commented on [Wed Dec 16 2015](https://github.com/VirtoCommerce/vc-platform/issues/175)

---

@OlegoO commented on [Tue Jul 25 2017](https://github.com/VirtoCommerce/vc-platform/issues/175#issuecomment-317697253)

I recommend to look on http://angular-slider.github.io/angularjs-slider/

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
