### ISSUE TITLE
Implement API for bulk update

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront#39]
@asvishnyakov commented on [Fri Sep 15 2017](https://github.com/VirtoCommerce/vc-storefront/issues/51)

In `ApiCartController` add copies of `AddItemToCart`, `ChangeCartItem`, `RemoveCartItem` method, but allow to pass multiple items instead of single, i.e.
```
AddItemToCart([FromBody] AddCartItem cartItem) → AddItemToCart([FromBody] AddCartItem[] cartItems)
```
In `CartBuilder` add copies of `AddItemAsync` & `AddLineItemAsync`, etc. and allow to pass multiple items instead of single, i.e.:
```
public class CartItem
{
    public Product Product { get; set; }
    public int Quantity { get; set; }
}

AddItemAsync(Product product, int quantity) → AddItemsAsync(IEnumerable<CartItem> items)
AddLineItemAsync(LineItem lineItem) → AddLineItemAsync(IEnumerable<LineItem> lineItems)
```

**Comment by asvishnyakov** [comment]
Depend on #41 to avoid a lot of API requests to platform

**Comment by Flanker72** [comment]
Implemented in XAPI data access layer. See `addItemsCart` mutation.
