### ISSUE TITLE
If store has "Allow anonymous user for store" setting disabled and can't find theme, it redirect to url with very long query

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront#401]
Version info:
- Platform version: v3 RC4 with some updates
- Storefront version: latest dev

### Expected behavior

Storefront should show usual error about lost theme

### Actual behavior

It redirect to something like
http://localhost:2082/en-US/Account/Login?ReturnUrl=%2fodt%2fen-US%2fcommon%2fnotheme%253FReturnUrl%3d%252fodt%252fen-US%252fcommon%252fnotheme%25253FReturnUrl%253d%25252fodt%25252fen-US%25252fcommon%25252fnotheme%2525253FReturnUrl%25253d%2525252fodt%2525252fen-US%2525252fcommon%2525252fnotheme%252525253FReturnUrl%2525253d%252525252fodt%252525252fen-US%252525252fcommon%252525252fnotheme%25252525253FReturnUrl%252525253d%25252525252fodt%25252525252fen-US%25252525252fcommon%25252525252fnotheme%2525252525253FReturnUrl%25252525253d%2525252525252fodt%2525252525252fen-US%2525252525252fcommon%2525252525252fnotheme%252525252525253FReturnUrl%2525252525253d%252525252525252fodt%252525252525252fen-US%252525252525252fcommon%252525252525252fnotheme%25252525252525253FReturnUrl%252525252525253d%25252525252525252fodt%25252525252525252fen-US%25252525252525252fcommon%25252525252525252fnotheme%2525252525252525253FReturnUrl%25252525252525253d%2525252525252525252fodt%2525252525252525252fen-US%2525252525252525252fcommon%2525252525252525252fnotheme%252525252525252525253FReturnUrl%2525252525252525253d%252525252525252525252fodt%252525252525252525252fen-US%252525252525252525252fcommon%252525252525252525252fnotheme%25252525252525252525253FReturnUrl%252525252525252525253d%25252525252525252525252fodt%25252525252525252525252fen-US%25252525252525252525252fcommon%25252525252525252525252fnotheme%2525252525252525252525253FReturnUrl%25252525252525252525253d%2525252525252525252525252fodt%2525252525252525252525252fen-US%2525252525252525252525252fcommon%2525252525252525252525252fnotheme%252525252525252525252525253FReturnUrl%2525252525252525252525253d%252525252525252525252525252fodt%252525252525252525252525252fen-US%252525252525252525252525252fcommon%252525252525252525252525252fnotheme%25252525252525252525252525253FReturnUrl%252525252525252525252525253d%25252525252525252525252525252fodt%25252525252525252525252525252fen-US%25252525252525252525252525252fcommon%25252525252525252525252525252fnotheme%2525252525252525252525252525253FReturnUrl%25252525252525252525252525253d%2525252525252525252525252525252fodt%2525252525252525252525252525252fen-US%2525252525252525252525252525252fcommon%2525252525252525252525252525252fnotheme

### Steps to reproduce
1. Open admin
1. Open store
1. Open settings
1. Disable "Allow anonymous user for store"
1. Open storefront appconfig.json
1. Set theme path to non-existing path

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-3749 has been created
