### ISSUE TITLE
cannot modify SEOInfo for certain storefront pages

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-storefront#43]
@alireza-salehi commented on [Mon Apr 03 2017](https://github.com/VirtoCommerce/vc-platform/issues/839)

Some pages like account, cart, login,register, contact, profile,reset password, customer order,customer addresses,...  are showing active store SEOInfo (title and description), problem exist in both Electronic and clothing theme.

i added following code to fix it as a workaround to desired controller actions (with hard coded slugs):

```
var seo = WorkContext.CurrentStore.SeoInfos.FirstOrDefault(x => x.Language == WorkContext.CurrentLanguage && x.Slug == "customers-account");
if (seo != null)
{
WorkContext.CurrentPageSeo = seo;
}

```

**Comment by Skrypt** [comment]
I think you can add this directly also in the RouteConfig.cs file.

`
routes.AddStorefrontRoute("ContactUs", "contact-us", defaults: new { controller = "StaticContent", action = "GetStaticTemplate", templateName = "contact-us", seoInfo = new SeoInfo { Title = "Contact Us", MetaDescription = "Contact us meta description", MetaKeywords = "meta keywords here" } });
`

**Comment by Woland2k** [comment]
@Skrypt  shouldn't be adding contact-us page as a route. You simply create a new page called contact-us and set template "page.contactus", you can then set url for the page as well

**Comment by Skrypt** [comment]
Seems like a more proper way to do this. 👍

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
