### ISSUE TITLE
Rename this repository to vc-storefront

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-storefront#445]

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-3237 has been created

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-3712 has been created

**Comment by OlegoO** [comment]
https://github.com/VirtoCommerce/vc-storefront
