### ISSUE TITLE
Add support of sass/scss importing

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront#45]
Currently, if I try to import sass/scss in processed sass/scss, it fails:

> Line: @import "_bootstrap-variables.scss"; Compiler error: stdin:2: file to import not found or unreadable: _bootstrap-variables.scss Current dir:

Possible, we just need to include path of currently processed sass/scss to IncludePath(s) property of SassOptions passed to sass compiler. Need more research about it.

**Comment by OlegoO** [comment]
Need to update libsaas to latest version

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
