### ISSUE TITLE
AsyncLock implementation isn't distributed

### ISSUE THREAD

**Issue by miguelhasse** [VirtoCommerce/vc-storefront#5]
AsyncLock should be implemented as a distributed lock to support multi-instance storefront scenarios.
(this could be accomplished using Redis when it is enabled - http://redis.io/topics/distlock)

**Comment by tatarincev** [comment]
Thanks for suggestions, цe have big expectations for the correct load balance distribution :)

**Comment by tatarincev** [comment]
The platform already has the support of hybrid cached data consistency policy.
https://virtocommerce.com/docs/vc2devguide/deployment/platform-scaleout
