### ISSUE TITLE
Changing theme settings doesn't work anymore

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-storefront#50]
@Woland2k commented on [Mon Sep 11 2017](https://github.com/VirtoCommerce/vc-theme-default/issues/3)

Changing theme preset from "Blue" to "Dark" doesn't work anymore. It still displays old blue theme.

**Comment by OlegoO** [comment]
Could not reproduce the problem on DEMO:

Changed theme from Blue to Dark and back
![image](https://user-images.githubusercontent.com/7639413/30750365-9ab76eaa-9fb6-11e7-9272-89c97554b464.png)

![image](https://user-images.githubusercontent.com/7639413/30750757-9cbbaf80-9fb7-11e7-9751-a8ba85e6c8b9.png)

@Woland2k Can you recheck?
