### ISSUE TITLE
Allow to pass custom attributes to form tag

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront#52]
Sometime we want customize default Shopify forms, i.e. add class, for example. Currently, it's not possible. But we may allow to pass custom attributes to form tag. i.e.
```
    {% form: 'customer_login', name: "customer_login", class: 'login-form-class' %}
```

without name attribute, for example, we can't validate form with angular.

**Comment by tatarincev** [comment]
In the storefront version since 4.0.0 al forms are defined as pure Html <form> tags in templates. So the current problem is no longer relevant.
