### ISSUE TITLE
Sold out badge

### ISSUE THREAD

**Issue by slang123** [VirtoCommerce/vc-storefront#53]
The sold-out badge is put on items when the "Is Buyable" is false on the catalog item.

The ProductAvailabilityService -> IsAvailable is used for this check.

In my opinion if the item is not buyable it does not meen it is sold out. I could be wrong..

**Comment by Woland2k** [comment]
@slang123 yes, I agree, it should be some other label, possibly "not available"

**Comment by slang123** [comment]
In my case I am disabling the Buy button. I'm using it to only show items that we sell in our physical store and that most likely would not be sold online anyway. But it is possible to ask for an RFQ on the item.

**Comment by OlegoO** [comment]
"Sold-out":
Given a product with Inventory.Quantity  < 0 and Can be purchased is true
When I open product's thumbnail or product page
Then I should see "sold-out badge" and ask for an RFQ on the item.

"Not available":
Given a product with any Quantity < 0 and Can be purchased is false
When I open product's thumbnail or open product page
Then I should see "not available badge" and don't see for an RFQ on the item.

**Comment by vkrashenko** [comment]
![default1](https://user-images.githubusercontent.com/29459286/31023449-20745cbc-a53c-11e7-8851-902a6bd88630.gif)

**Comment by tatarincev** [comment]
Associate issue https://github.com/VirtoCommerce/vc-theme-default/issues/12
https://github.com/VirtoCommerce/vc-theme-default/issues/12

**Comment by asvishnyakov** [comment]
Approved and merged. Now, if product is not available (not active and not buyable) "Unavailable" badge shows, while if product is sold-out (i.e. no products in fulfillment center) "Sold out" badge shows.
Thank you, @vkrashenko !
