### ISSUE TITLE
Can't see any products when user added to usergroup

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront#54]
In gitter client says:

> something strange is happening when i add a usergroup to a customer. At first I see no products in storefront. But then i log out and back in again and it works again. Then I add some marketing for the usergroup, like 20% off and everything starts to disappear again. I tried it on the demo site aswell. Am I doing something wrong or can someone else confirm this?
heh, I tried opening the store in other browsers and there are no products showing. So it doesn't seem like a cache issue

To reproduce:
1. Create account in storefront
2. Log in
3. Go to admin and add any usergroup to your user

Now you can't see any products in storefront

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.0.2
