### ISSUE TITLE
Property localization

### ISSUE THREAD

**Issue by slang123** [VirtoCommerce/vc-storefront#55]
The product properties are not being translated on the product page. The Property Name is being used.

On collection page filters it is working fine.

![german](https://user-images.githubusercontent.com/7000708/31014109-3515f430-a511-11e7-826d-455ad9312a2c.PNG)

**Comment by vkrashenko** [comment]
![delocal](https://user-images.githubusercontent.com/29459286/31391956-4af1c0b6-add8-11e7-8ef4-124dbf67e1f8.gif)

**Comment by tatarincev** [comment]
Why did you replace Liquid property details rendering to client-side script rendering, it is absolutely different approaches (server rendering - for SEO purposes, client rendering - for data actualization) and they should work simultaneously?
