### ISSUE TITLE
Make product visibility on Home Page.

### ISSUE THREAD

**Issue by nani28** [VirtoCommerce/vc-storefront#563]
How to display all products to specific category on Home page of theme??

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6708 has been created

**Comment by OlegoO** [comment]
Here can be a good example. How to display the products from specific category. 
 
https://github.com/VirtoCommerce/vc-theme-default/blob/8e2639ad45717341d314b8750f40fd55a64d5e2c/templates/index.liquid#L144-L156

Another solution, do it via Storefront API. Just do call from JavaScript and render it.
