### ISSUE TITLE
When all products with in particular category are display on screen at that time I want to display description of product along with price. Is there any way to configure this requirement.

### ISSUE THREAD

**Issue by nani28** [VirtoCommerce/vc-storefront#564]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: 
- Platform version: 
- Storefront version: 

### Steps to reproduce
1.
2.
3.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6793 has been created

**Comment by OlegoO** [comment]
Use  {{ product.description }}

And don't forget to adjust the response group and load description. By default, a description is not loaded for collection.

For example, I did it via the query string. You can do it via either code or settings.

![image](https://user-images.githubusercontent.com/7639413/106494031-928bca80-64c2-11eb-8648-c06c077a1e37.png)
