### ISSUE TITLE
Can I define multiple price for perticuler product? for e.g. There is one digital product with subscription for that price are different weekly based, monthly based, yearly based etc. If "Yes" then How can I display all price as form of dropdown in section of price?

### ISSUE THREAD

**Issue by nani28** [VirtoCommerce/vc-storefront#565]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: 
- Platform version: 
- Storefront version: 

### Steps to reproduce
1.
2.
3.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7429 has been created

**Comment by OlegoO** [comment]
Yes. You can define multiple prices in different price lists, then you can call

​/api​/products​/{productId}​/prices
​/api​/pricing​/evaluate

to return multiplece prices and display them for the client.

Also you can create a new variation for each digital product with subscription and assign own price for each.
