### ISSUE TITLE
[Question] Pre release with dev branch

### ISSUE THREAD

**Issue by CKGrafico** [VirtoCommerce/vc-storefront#567]
Hello in here https://github.com/VirtoCommerce/vue-starter-theme/issues/5 you recommended me to use /dev version but I think there is no pre release from that branch is that possible or we have to download dev branch and compile instead of work with the binaries?

**Comment by tatarincev** [comment]
I recommended you take the `starter-theme` from `dev` branch https://github.com/VirtoCommerce/vue-starter-theme/tree/dev. What about the storefront, you have to use this branch https://github.com/VirtoCommerce/vc-storefront/tree/feature/x-api-integration. The `starter-theme/dev` works only with the storefront version from this branch.

**Comment by tatarincev** [comment]
We still have no binary artifacts for these versions. And you have to work with the source code until we publish them. Excuse for the inconvenience. :)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6930 has been created

**Comment by CKGrafico** [comment]
It's ok thanks @tatarincev

**Comment by CKGrafico** [comment]
It is very strange that with this branch I've the following error, but it is probably my fault, thanks, I'll check tomorrow what is exactly happening.

![image](https://user-images.githubusercontent.com/2048511/107274029-2d9b1c00-6a50-11eb-8268-b1a1238e7c8e.png)
