### ISSUE TITLE
3 test fails on storefront

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront#58]
`SerializationTests` and `ShoppingCartTests` fails, but because they don't have `Trait` attribute, storefront successfully builded on CI

**Comment by Andrew-Orlov** [comment]
These tests are currently not passing. Should they be included in the CI?

**Comment by Andrew-Orlov** [comment]
Fixed shopping cart and serialization tests. Shopping cart test was added to `Integration` category, serialization tests was added to `Unit` category.

**Comment by asvishnyakov** [comment]
@Andrew-Orlov Formally you fixed problem described in this issue. So thank you for your work.
But I think the problem is little more complex: I think we must find (in storefront) and analyze all tests not marked with Trait attribute and then do one of the following: remove test as invalid or fix it (if it's outdated or has wrong implementation) and then mark it as unit or integration test.

**Comment by asvishnyakov** [comment]
@Andrew-Orlov  Look at *all* tests, verify what they valid (i.e. if ProductAvailabilityTest tests all cases when product may be valid and not) and mark this tests with Trait attribute if they valid or create issue to fix test if it is not valid.

**Comment by OlegoO** [comment]
Will create a new ticket for all tests and verify what they valid
