### ISSUE TITLE
Replace DotLiquid with Liquid.NET

### ISSUE THREAD

**Issue by miguelhasse** [VirtoCommerce/vc-storefront#6]
Well the title say it all... unlike DotLiquid which is a grammarless parser, https://github.com/mikebridge/Liquid.NET is a grammar based parser providing more reliable rendering results and extensibility (as an AST is built by the parser). It also opens the way to implementing a language service for Liquid templates.

**Comment by tatarincev** [comment]
Thanks for resource! We will soon begin migration storefront to ASP.NET Core and maybe changing Liquid engine.  Also we have some plans to write sample theme based on Razor view engine.

**Comment by tatarincev** [comment]
Replaced to Scriban https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.0.0
