### ISSUE TITLE
Unable to run vc default theme for Electronics store on Storefront version 6.1.0

### ISSUE THREAD

**Issue by shubhamdhanetia** [VirtoCommerce/vc-storefront#608]
Hello Team,

I tried running the latest storefront version 6.1.0 for the VC default theme for Electronics Store but it is giving errors.

But when I tried running the same theme in version 5.8.1, it is working fine.

![image](https://user-images.githubusercontent.com/71070755/170843108-5fa85990-46ed-402f-a976-c632b2850f59.png)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8050 has been created

**Comment by DanilBayushev** [comment]
Hello @shubhamdhanetia !
The latest storefront version 6.1.0 is only compatible with the Vue B2B theme. See the deprecation warning block [here](https://github.com/VirtoCommerce/vc-theme-default).
