### ISSUE TITLE
Implement TODOs in storefront

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront#61]
Storefront has 14 TODO comments now. Implement them or remove because of fixed / won't fix.
TODOs include:
- Indexed search for Vendors
- Caching for customers
- Resource manager for Azure Blog Storage
- Login expiration issue

**Comment by tatarincev** [comment]
Seems most of these TODOs have already implemented or no longer relevant.
You may reopen this issue if it has been closed in error.
