### ISSUE TITLE
"C" in СontactForm is cyrillic capital letter "es"

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront#63]
https://github.com/VirtoCommerce/vc-storefront/blob/294524a415d830367f524d813c4ff02228027ed4/VirtoCommerce.Storefront/App_Start/RouteConfig.cs#L163
https://github.com/VirtoCommerce/vc-storefront/blob/294524a415d830367f524d813c4ff02228027ed4/VirtoCommerce.Storefront/Controllers/CommonController.cs#L63

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.0.2
