### ISSUE TITLE
Shouldn't reset firstname, lastname and email when password policy is not met

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-storefront#65]
The values should remain even when password policy is not met.

![image](https://user-images.githubusercontent.com/1566470/32019197-4186d2c8-b981-11e7-852c-d3f82974f41f.png)

**Comment by vkrashenko** [comment]
![t0eljdnoqe](https://user-images.githubusercontent.com/29459286/33071820-bab09cac-cec5-11e7-9aac-a0ee77b947fd.gif)
